### PR TITLE
Bump to `actions/checkout@v3`

### PR DESCRIPTION
**Pull request by magnetikonline**
**Description:**

- Bump `actions/checkout` to `@v3`
- Also noted (and bumped) `actions/upload-artifact` to `@v3` (released after I cut this PR).

https://github.com/actions/checkout/releases/tag/v3.0.0

**Related issue:**
N/A

**Check list:**
- [ ] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

### CODE REVIEW

**Comment by magnetikonline** [comment]
ping @brcrista

**Comment by vsafonkin** [comment]
Hi @magnetikonline, perhaps, it would be better to include these changes to #433 , what do you think?

**Comment by magnetikonline** [comment]
> Hi @magnetikonline, perhaps, it would be better to include these changes to #433 , what do you think?

thanks @vsafonkin - typically I like to keep these PRs as small a changeset as possible so they are easier to reason with - hence the dual PRs - but if it's easier - can certainly combine them.

**Comment by brcrista** [comment]
I went ahead and merged #433, so we can just move forward with this one separately.  Looks like there are some merge conflicts now.

**Comment by magnetikonline** [comment]
Done @brcrista - just re-created from `main` and added a bump for `actions/upload-artifact` too.

**Comment by magnetikonline** [comment]
Hrm - noted one of the Yarn 2 e2e tests is now failing. Can't see how these changes introduce this issue?

Screen Shot 2022-04-01 at 2 01 59 pm

**Comment by dmitry-shibanov** [comment]
Hello @magnetikonline. Thank you for your pull request. I think it was a random issue. I've resolved it by rerunning. Is pull request ready?

**Comment by magnetikonline** [comment]
Wonderful @dmitry-shibanov - yeah all tests now passing 👍 

Ready for approval/merge.

**Review by dmitry-shibanov — APPROVED** [review]

**Review by vsafonkin — APPROVED** [review]

**Review by girlsavenue1 — COMMENTED** [review]
@vsafonkin

**Pull request merged**
