### PR TITLE
Only override NODE_AUTH_TOKEN with a placeholder if it isn't already set, e.g. in jobs.<job_id>.env

### PR DESCRIPTION
**Pull request by martinjlowm**
This enables NODE_AUTH_TOKEN to be set globally for all steps within a job or for all jobs within a workflow as is described here: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#env and https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idenv

### CODE REVIEW

**Comment by mangs** [comment]
I was just about to file this exact PR. Hoping this can get some attention.

**Comment by mangs** [comment]
Wasn't sure who to contact for an update. I just picked the most recent, frequent committer.

**Comment by zodman** [comment]
i thing overwrite the env without a notice or message or echo ... will fix a lot of dev's pain.

**Comment by zodman** [comment]
this PR goes to old!

**Comment by maxim-lobanov** [comment]
We have merged https://github.com/actions/setup-node/pull/205 recently and released `actions/setup-node@v2` with fix.

**Pull request closed without merging**
