### PR TITLE
feat: add volta as node-version-file

### PR DESCRIPTION
**Pull request by jef**
**Description:**

Unlike other version managers, Volta places its versioning within `package.json`. We will check for `volta.node` to see if there is an value and use `engines.node` as backup. This is an important distinction, as `volta.node` should supersede `engines.node`.

**Check list:**

- [x] Mark if documentation changes are required.
- [x] Mark if tests were added or updated to cover the changes.

### CODE REVIEW

**Review by funkswing — APPROVED** [review]

**Comment by dmitry-shibanov** [comment]
Hello @jef. Thank you for your pull request. Could you please run the `npm run format` command ? Besides, do we need to declare package.json as possible input ?

**Comment by jef** [comment]
> Besides, do we need to declare package.json as possible input

great question. i also wasn't sure about this. i'm not sure if other projects use `package.json` for storing node.js versions. if so, then perhaps this could be more extendable.

**Comment by dmitry-shibanov** [comment]
Thank you for reply @jef. I think we can remove package.json from this pull request because we have pull requests with adding support for package.json engine.

**Comment by jef** [comment]
> pull requests with adding support for package.json engine.

ah, yes. i see that in #485. in this case, i believe there need some logic update into include volta.

should i wait until #485 is merged and then i proceed with mine?

**Comment by vsafonkin** [comment]
Hi @jef, could you please update your branch from `main` and resolve conflicts?

**Comment by jef** [comment]
Sure thing. I'll be back from vacation next week.

**Comment by jef** [comment]
Should be all good now @vsafonkin. Thanks!

**Review by vsafonkin — APPROVED** [review]

**Review by marko-zivic-93 — APPROVED** [review]

**Comment by jef** [comment]
I've realized that the documentation for `package.json` is missing. Should I add it in here?

**Comment by dmitry-shibanov** [comment]
Hello @jef. Thank you for your suggestion. We would appreciate if you add this to the documentation, but if you want, we will do it on our side. Thank you!

**Review by puskuruk — APPROVED** [review]

**Comment by jef** [comment]
Alright, I've added in the documentation! Everything seems good from my end. Let me know if you need anything extra.

**Review by marko-zivic-93 — APPROVED** [review]

**Comment by vsafonkin** [comment]
Hi @jef, you need to resolve conflicts according #553 Thank you in advance!

**Comment by jef** [comment]
> Hi @jef, you need to resolve conflicts according #553 Thank you in advance!

Not a problem! Should be all sorted. I removed the try/catch on the latter half of `parseNodeVersionFile` only because it was throwing an error locally. Seemed better this way. I can revert if necessary.

Thanks!

**Comment by jef** [comment]
@vsafonkin, anything else you need before getting this in? Thanks!

**Comment by dmitry-shibanov** [comment]
Hello @jef. Sorry for the late response. Could you please e2e tests for volta ?

**Comment by e-korolevskii** [comment]
Hi @jef!

Just a gentle ping - we would like to know if you are planning to implement e2e tests here.

Thank you in advance!

**Comment by jef** [comment]
Sorry about that. Yes, I can implement some e2e tests. Is that going to be outside of the `__tests__/installer.test.ts` file?

**Comment by e-korolevskii** [comment]
Hello @jef! 

Thanks for the quick response! 
According to our [contributor's guide](https://github.com/actions/setup-node/blob/main/docs/contributors.md), end-to-end tests are in the [workflows](https://github.com/actions/setup-node/tree/main/.github/workflows) folder, particularly in the [versions.yml](https://github.com/actions/setup-node/blob/main/.github/workflows/versions.yml) file.

**Comment by jef** [comment]
Hi @e-korolevskii, I believe I implemented something that should work. I can also combine it with the previous step if that makes more sense.

Thanks!

**Review by e-korolevskii — APPROVED** [review]

**Comment by e-korolevskii** [comment]
Hi @jef!

Now it looks good and I think we are ready to merge it.
I just wanted to thank you again for your contribution!

**Review by vsafonkin — APPROVED** [review]

**Comment by jef** [comment]
Thanks for walking me through @e-korolevskii 😊

**Review by marko-zivic-93 — APPROVED** [review]

**Pull request merged**
