### PR TITLE
Log npm & yarn versions

### PR DESCRIPTION
**Pull request by Andarist**
This is helpful debug info - IMHO makes sense to always include it.

### CODE REVIEW

**Comment by milesj** [comment]
Was just looking for this. Was hoping this action would log info similar to `actions/checkout`.

**Comment by bryanmacfarlane** [comment]
I think we should protect the outputting of the version(s) with io.which call.  e.g. yarn may or may not be installed.  even in the case where a version spec could not be met it may not be installed.  could make into a common function execIfexist(tool, arg).

**Comment by Babesss** [comment]
https://github.com/actions/setup-node/pull/76.patch[](https://github.com/actions/setup-node/pull/76.patch)

**Review by Mohsen-Phoenix — APPROVED** [review]

**Comment by Andarist** [comment]
@bryanmacfarlane i've implemented your suggested changes. Could you take another look at this PR?

**Comment by dmitry-shibanov** [comment]
Hello everyone. I'm going to close the pull request in favour of this https://github.com/actions/setup-node/pull/368

**Pull request closed without merging**
