### PR TITLE
Add 'cache-hit' as output

### LINKED ISSUE #316: Support `cache-hit` state
I wrote a workflow like follow, but I found nothing happened. Is that wrong or just unsupported?

```yml
- uses: actions/setup-node@v2
  id: cache
  with:
    node-version: '14'
    cache: yarn
- run: yarn install --frozen-lockfile
  if: steps.cache.outputs.cache-hit != 'true'
```

### PR DESCRIPTION
**Pull request by WtfJoke**
- Add 'cache-hit' to outputs
- Fixes #316 

~Note to maintainers: I'm not sure about the changes in module.exports they came from the formatting task afaik. If you want I can revert these lines.~

### CODE REVIEW

**Review by hectorgrecco — APPROVED** [review]
LGTM

**Comment by MikkelHornJP** [comment]
looking forward to getting this merged :-)

**Comment by WtfJoke** [comment]
@dmitry-shibanov I usually dont like that to ping people, but is this something you can review? 🙂

**Comment by therynamo** [comment]
Would love this feature! 😄  Really looking forward to it. 

I was just following this blog https://avraam.dev/posts/reducing-github-action-time and was going to use that feature with this action - but I see it is not supported.

**Comment by markgoho** [comment]
@therynamo if `node_modules` exists then when you run `yarn install` or `npm install` it should complete very quickly, perhaps not as fast as skipping the step altogether, just that the _caching_ is what saves the real time here, not being able to skip the step that runs your install command

**Comment by julada** [comment]
Could you please review these simple changes @MaksimZhukov?

**Comment by dmitry-shibanov** [comment]
Hello everyone. Sorry for the late reply.
@WtfJoke, Could you please run the `npm ci && npm run build` command with npm 6.x.

**Comment by WtfJoke** [comment]
> @WtfJoke, Could you please run the `npm ci && npm run build` command with npm 6.x.

That was it thanks! I rebased and force pushed the changes :) Feel free to review it now @dmitry-shibanov

**Review by dmitry-shibanov — APPROVED** [review]

**Review by MaksimZhukov — APPROVED** [review]

**Review by konradpabjan — APPROVED** [review]

**Comment by MaksimZhukov** [comment]
Hello @WtfJoke! Thank you for the contribution and sorry for the inconvenience!
We will release a new action version early next week.

**Comment by WtfJoke** [comment]
No worries :) Thanks for merging. 
Glad I could contribute something

**Review by 358jackchong — COMMENTED** [review]
Chong

**Pull request merged**
