### PR TITLE
set node-version output

### LINKED ISSUE #150: Provide a output for the selected Node.js version
It would be great if there could be an output that tells which exact version of Node.js was installed.

An example use case for this is cacheing `node_modules`, which is only valid for the same OS + Node.js version + package-lock combination:

```yml
name: Node CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      id: setup-node
      uses: actions/setup-node@v1
      with:
        node-version: 12.15.0

    - name: Cache dependencies
      id: cache-node-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ steps.setup-node.outputs.node-version }}-modules-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      run: npm ci
      if: steps.cache-node-modules.outputs.cache-hit != 'true'

    - name: Tets
      run: npm test
```

### PR DESCRIPTION
**Pull request by panva**
This PR adds `node-version` to the action output.

closes #150

### CODE REVIEW

**Comment by panva** [comment]
@MaksimZhukov is this something you may look into?

**Comment by btkostner** [comment]
Can we get some movement on reviewing this PR? This output is needed to make a better cache key (invalidate when minor version increases.)

**Comment by LinusU** [comment]
ping @0xdeafcafe @dmitry-shibanov, would any of you be able to review/merge this? ☺️

**Review by 0xdeafcafe — APPROVED** [review]

**Comment by 0xdeafcafe** [comment]
I would love to merge, but I'm not a project owner @LinusU 😅

**Comment by panva** [comment]
@dmitry-shibanov @MaksimZhukov going by the upvotes this is a sought after feature.

**Review by Mmkred — APPROVED** [review]

**Review by calbearox — COMMENTED** [review]
@maldito-dot

**Comment by LinusU** [comment]
ping @dmitry-shibanov, any chance of landing this?

**Comment by panva** [comment]
Superseded by #534

**Pull request closed without merging**
