### PR TITLE
V3.7.0

### PR DESCRIPTION
**Pull request by devlynnx**
**Description:**
Describe your changes.

**Related issue:**
Add link to the related issue.

**Check list:**
- [x] Mark if documentation changes are required.
- [x] Mark if tests were added or updated to cover the changes.

### CODE REVIEW

**Review by Vue-Pu — APPROVED** [review]
#765

**Comment by Vue-Pu** [comment]
@ganta review

**Review by Vue-Pu — APPROVED** [review]
merge into `main` from
 `.github/workflows/update-config-files.ym`l

**Comment by dmitry-shibanov** [comment]
Hello everyone. I'm going to close the pull request because it looks like a spam. Feel free to ping us when you fill out the pull request form.

**Pull request closed without merging**
