### PR TITLE
Create setup-node

### PR DESCRIPTION
**Pull request by dakgk**
**Description:**
Describe your changes.

**Related issue:**
Add link to the related issue.

**Check list:**
- [ ] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

### CODE REVIEW

**Comment by magnetikonline** [comment]
@brcrista just spam.

Noted a few of these PRs from this user. Not exactly sure the best method to report these users with GitHub?

**Comment by vsafonkin** [comment]
@magnetikonline 
Screenshot 2022-04-01 at 9 14 08 AM

**Comment by vsafonkin** [comment]
Spam

**Comment by magnetikonline** [comment]
Thx @vsafonkin 👍

**Pull request closed without merging**
