### PR TITLE
upgrade `@action/cache` to 3.0.4 to fix stuck issue

### PR DESCRIPTION
**Pull request by islishude**
**Description:**

`@action/cache` 3.0.3 fixs a download  stuck issue

checkout https://github.com/actions/toolkit/blob/main/packages/cache/RELEASES.md#303

**Related issue:**

https://github.com/actions/cache/issues/810

**Check list:**
- [ ] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

### CODE REVIEW

**Comment by dmitry-shibanov** [comment]
Hello @islishude. Thank you for your pull request. Could you please use [licensed](https://github.com/github/licensed) too to regenerate licenses.

**Review by dmitry-shibanov — APPROVED** [review]
Could please fix a version in the title because the actual version is 3.0.4

**Comment by islishude** [comment]
> Could please fix a version in the title because the actual version is 3.0.4

Done

**Comment by dmitry-shibanov** [comment]
Thank you. We'll ping you when we release a new version of the action. For the testing you can use commit of the changes.

**Pull request merged**
