### PR TITLE
Fixed auth GPR

### PR DESCRIPTION
**Pull request by valmirphp**
I had the same issues mentioned in the issues:
- #53 
- #52 
- #49

Analyzing the code I realized that the file `/home/runner/work/_temp/.npmrc`  was defective.

- run: cat /home/runner/work/_temp/.npmrc

Output:
```
 //npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}
```

> Fix string replace to concatenate NODE_AUTH_TOKEN

### CODE REVIEW

**Comment by negebauer** [comment]
The idea behind the current code, as I understand it, is so that the token isn't saved in the file.
When running commands like `npm install` you can pass the token and it works, as shown in the _Use private packages_ section of the [README](https://github.com/actions/setup-node/blob/master/README.md).

```yaml
- run: npm install
  env:
    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```

**Comment by valmirphp** [comment]
@negebauer  do you run "npm install" with github private packages, following this example?

**Comment by negebauer** [comment]
Yes, and it works.

```yml
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com
          scope: '@mtblc'
      # From https://github.com/actions/setup-node "Use private packages:"
      # Skip post-install scripts here, as a malicious
      # script could steal NODE_AUTH_TOKEN.
      - run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MTBLC_NPM_TOKEN }}
```

Thats the code I'm running

**Comment by getify** [comment]
@negebauer it's broken for many of us (as evidenced in the threads linked by the OP).

**Comment by getify** [comment]
@valmirphp Does npmrc format support a bash-like syntax for pulling the token from the shell environment? If so, wouldn't it be preferable to access it that way?

If not, then it seems like the only way is what you're doing, which is dropping in the NPM token into the auto-generated npmrc.

**Comment by negebauer** [comment]
It does read the token from the shell environment when running `npm install`. You can test that by doing it locally. Modify your `.npmrc` to use an env var, export the env var and `npm install`.

**Comment by getify** [comment]
I think this is actually the problem:

https://github.com/actions/setup-node/blob/master/src/authutil.ts#L57

I think the `NODE_AUTH_TOKEN` environment variable itself is not in fact being exported correctly, not that npmrc isn't picking it up.

It would be useful to verify if that's indeed the case.

**Comment by negebauer** [comment]
That's an empty export on the `setup-node` action. When running `npm install` you should pass `NODE_AUTH_TOKEN` as an env variable. This way the actual token is only available on the install action.

**Comment by getify** [comment]
@negebauer I don't think you're understanding the context of the problems being face. Have you read #52?

**Comment by negebauer** [comment]
Yes I have, but this doesn't fix that. This PR writes a particular env var to `.npmrc` which doesn't need to be written in this step, since it's read from the environment on the steps that actually need it.

**Comment by valmirphp** [comment]
@getify you are absolutely right.

`.npmrc` supports variable ENV, which is the best way to work without physically saving the token.

The PR I created solves this authentication problem, but I believe the way is to solve the export problem.

I will close this PR, and I will look for a new solution.

For now if anyone wants can use my fork, follows example:


```yml
name: Test Setup Node

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node: [ '10', '8' ]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: valmirphp/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://npm.pkg.github.com'
        always-auth: false
        scope: '@your-organization'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN_NPM }}
    - name: Installation
      run: yarn install
      env:
        CI: true
```

**Pull request closed without merging**
