### PR TITLE
Allow using .tool-versions for node-version-file

### PR DESCRIPTION
**Pull request by deiga**
**Description:**
Add parsing of `.tool-versions` file format.
This enables developers which use `asdf` to use their version file to
steer which version of node to install.
This change should be fully backwards compatible as it only does things
if a certain string is found in the `node-version-file`

**Check list:**
- [x] Mark if documentation changes are required.
- [x] Mark if tests were added or updated to cover the changes.

### CODE REVIEW

**Review by Johnstone456 — APPROVED** [review]

**Comment by brcrista** [comment]
Hey @deiga, thanks for the PR.  This is my first time hearing about `asdf`, but I think the approach makes sense.  If I'm understanding correctly, you don't actually have to install `asdf` on the build machine; this is just adding support for its syntax.  Is that right?

Since this is a new feature, if you're able to put together a minimal workflow that uses `deiga/setup-node`, that would go a long way towards helping us see how it works.

**Comment by runlevel5** [comment]
Thanks for the PR, we are also using `asdf` for our projects (due to mix-tech nature). Love to see this PR going in

**Comment by IvanZosimov** [comment]
@deiga, 👋 Just a gentle ping 💌

**Comment by dmitry-shibanov** [comment]
Hello @deiga. Thank you for your pull request. For now I'm going to close the pull request because the logic was implemented in this [pull request](https://github.com/actions/setup-node/pull/373). If you have any concerns feel free to ping us.

**Pull request closed without merging**
