### PR TITLE
chore: Remove strategy for non-matrix builds

### PR DESCRIPTION
**Pull request by nschonni**
Just flagged in schema validation because the strategy value is only applicable if it has a matrix below it

### CODE REVIEW

**Comment by bryanmacfarlane** [comment]
Is the schema validation wrong?  Even though there's no matrix below there are multiple jobs and the intent is to fail fast the other jobs if one fails to release concurrency.  Not sure this is a good change but maybe I'm missing something ...

**Comment by nschonni** [comment]
The separate `job`s aren't part of a matrix. EX: if one fails it doesn't fail/cancel the others. The matrix is used to pass variables to them. If the one of the "batches" like running Node 14 and Node 12 fails, then it cancels all the jobs in the other batch, not other jobs in the same batch.

**Comment by nschonni** [comment]
Found the schema that VS Code is using https://json.schemastore.org/github-workflow

**Comment by bryanmacfarlane** [comment]
It might be a bug in the schema - in this case we want fail fast even though it's not a matrix.

**Comment by nschonni** [comment]
Did an example to show that it doesn't behave like you're talking about https://github.com/nschonni/setup-node/actions/runs/499393700
Even if one of the job fails, it doesn't cancel other running jobs like it does when they are part of an actual matrix

**Review by theifedayo — COMMENTED** [review]
what does strategy: failfast: false do? can you explain?

**Review by MaksimZhukov — APPROVED** [review]

**Review by dmitry-shibanov — APPROVED** [review]

**Pull request merged**
