### PR TITLE
feat: handling the case where "node" is used for tool-versions file.

### PR DESCRIPTION
**Pull request by xytis**
**Description:**
Recent changes in RTX renamed 'nodejs' to 'node' in .tool-versions file.

I am not aware who is responsible for the actual naming convention in .tool-versions file.

This change allows consuming both 'nodejs' and 'node' identifiers.

### CODE REVIEW

**Comment by xytis** [comment]
@dmitry-shibanov done.

**Comment by dmitry-shibanov** [comment]
Hello @xytis. Thank you for your changes. Could you please add e2e test to versions.yml for this case?

**Comment by xytis** [comment]
@dmitry-shibanov done.

**Comment by dmitry-shibanov** [comment]
@xytis Could you please run the `npm run format` command?

**Review by dmitry-shibanov — APPROVED** [review]

**Comment by xytis** [comment]
Thanks.

**Comment by Shogun7711** [comment]
> **Description:** Recent changes in RTX renamed 'nodejs' to 'node' in .tool-versions file.
> 
> I am not aware who is responsible for the actual naming convention in .tool-versions file.
> 
> This change allows consuming both 'nodejs' and 'node' identifiers.

**Pull request merged**
