### PR TITLE
Main

### PR DESCRIPTION
**Pull request by precha1989**
**Description:**
Describe your changes.

**Related issue:**
Add link to the related issue.

**Check list:**
- [x] Mark if documentation changes are required.
- [x] Mark if tests were added or updated to cover the changes.

### CODE REVIEW

**Review by precha1989 — COMMENTED** [review]
#706 #147 #763 #778

**Comment by precha1989** [comment]
> **Description:** Describe your changes.
> 
> **Related issue:** Add link to the related issue.
> 
> **Check list:**
> 
> * [x]  Mark if documentation changes are required.
> * [x]  Mark if tests were added or updated to cover the changes.

**Comment by dmitry-shibanov** [comment]
Hello @precha1989. For now I'm going to close the pull request because it looks like a spam. Feel free to feel out the form and ping us.

**Review by precha1989 — COMMENTED** [review]
Duplicate of #

**Pull request closed without merging**
