### PR TITLE
Add npm-version option

### PR DESCRIPTION
**Pull request by frbuceta**
This change adds an option which allows to install a different version of NPM

### CODE REVIEW

**Review by lastthyme — APPROVED** [review]

**Comment by mattstrayer** [comment]
This would be a very welcomed feature. Can we get this out the door?

**Comment by mellis481** [comment]
@frbuceta Are you able to see this PR through please?  Would be great to get this in.

**Review by pierresisson — APPROVED** [review]
LGTM

**Comment by sztadii** [comment]
@frbuceta would you like to resolve the conflicts? I was thinking to implement this feature by myself, but in this case, you will lose the whole glory :(

**Comment by sztadii** [comment]
It looks like the forked repo does not exist, so we can not resolve the conflicts. Should we close the PR?

**Comment by brcrista** [comment]
@sztadii yes, we'll have to do that to make progress.

Looks like a useful feature.  But rather than adding a separate input, perhaps we should just support [`engines.npm`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#engines) as we are with `engines.node`: https://github.com/actions/setup-node/pull/485

**Pull request closed without merging**
