### PR TITLE
Add support for node version codenames and keywords

### LINKED ISSUE #26: Support aliases like LTS
Right now, we're thinking it makes sense to support `lts`, `latest`, `current`, and LTS version names (e.g. `dubinium`)

### PR DESCRIPTION
**Pull request by JimiC**
Resolves #26

This PR adds support for node codenames (`argon`, `boron` etc) and selected keywords (`latest`, `current`, `lts`).

Resolving the codenames and keywords is fully automated and ensures future codenames support.

In order to do so, I took the liberty to refactor the code and test cases for better optimization and maintainability.

I'm aware that code reviewing will be a nightmare because of the many changes. I suggest having a look at the new code itself instead, to have a better understanding of it.

In case the refactoring is not acceptable, I'll try to provide a PR with minimum changes, but the code will be ugly.

### CODE REVIEW

**Comment by JimiC** [comment]
Suggestion: Since the refactoring done in this PR interferes with #42, I could also incorporate those changes in this PR.

**Comment by DanielRuf** [comment]
`latest` would be great, as a solution you can already use `'*'`.

**Comment by ExE-Boss** [comment]
This PR seems to have a lot of out of scope changes in it.

**Comment by JimiC** [comment]
Not going to update it if it's not going to be merged.

**Comment by wdanilo** [comment]
Why is this not merged? It would be important to me to indicate that I want my tests to run on the latest LTS node version. Right now I need to update it everywhere by hand.

**Comment by maxim-lobanov** [comment]
Fixed in https://github.com/actions/setup-node/pull/270

**Pull request closed without merging**
